// English to Uzbek translation function
function translateToUzbek(word) {
  const translations = {
    Accept: "Qabul qilmoq",
    Achieve: "Erishmoq",
    Act: "Amal qilmoq",
    Adapt: "Moslashtirmoq",
    Add: "Qo'shmoq",
    Admire: "Hayrat bilan qarashmoq",
    Advise: "Maslahat berish",
    Agree: "Kelishmoq",
    Aim: "Maqsad qilmoq",

    Analyze: "Tahlil qilmoq",
    Apologize: "Uzr so'ramoq",
    Apply: "Murojaat qilmoq",
    Appreciate: "Qadrlamoq",
    Approve: "Tasdiqlamoq",
    Argue: "Munozara qilmoq",
    Arrive: "Yetib kelmoq",
    Ask: "So'ralmoq",
    Assist: "Yordam bermoq",
    Attack: "Hujum qilmoq",
    Attract: "Jazolamoq",
    Bake: "Pishirmoq",
    Bathe: "Yuvmoq",
    Behave: "Ravishda bo'lmoq",
    Believe: "Ishonmoq",
    Belong: "Tegishli bo'lmoq",
    Bet: "Shart qo'yish",
    Borrow: "Qarz olmoq",
    Build: "Qurmoq",
    Buy: "Sotib olish",
    Calculate: "Hisoblash",
    Call: "Qo'ng'iroq qilmoq",
    Care: "E'tibor bermoq",
    Carry: "O'tkazmoq",
    Catch: "Tortmoq",
    Change: "O'zgartirmoq",
    Choose: "Tanlash",
    Clean: "Tozalash",
    Climb: "Chiqmoq",
    Collect: "To'plamoq",
    Come: "Kelmoq",
    Communicate: "Aloqada bo'lmoq",
    Compare: "Taqqoslash",
    Complain: "Shikoyat qilmoq",
    Complete: "Yakunlamoq",
    Contribute: "Qo'shimcha hissa qo'shmoq",
    Cook: "Oshirish",
    Cost: "Narxi",
    Count: "Hisoblash",
    Create: "Yaratmoq",
    Cry: "Yig'lamoq",
    Dance: "Raqs qilmoq",
    Decide: "Qaror qabul qilmoq",
    Decorate: "Suzmoq",
    Defend: "Difolat qilmoq",
    Delay: "To'xtatmoq",
    Deliver: "Yetkazib berish",
    Depend: "Bog'liq bo'lmoq",
    Describe: "Tavsif qilmoq",
    Design: "Dizayn qilmoq",
    Destroy: "Yok etmoq",
    Develop: "Rivojlantirmoq",
    Discover: "Topmoq",
    Discuss: "Munozara qilmoq",
    Divide: "Bo'lishmoq",
    Do: "Amal qilmoq",
    Dream: "Tushuntirmoq",
    Dress: "Libos kiyish",
    Drink: "Ichmoq",
    Drive: "Haydash",
    Earn: "Daromad qilmoq",
    Eat: "Yemoq",
    Edit: "Tahrirlamoq",
    Educate: "O'qitmoq",
    Embrace: "Qabul qilmoq",
    Employ: "Ishga olish",
    Encourage: "Yo'llamoq",
    Enjoy: "Mazza olish",
    Enter: "Kirish",
    Escape: "Qochmoq",
    Establish: "Tashkil qilmoq",
    Evaluate: "Baholamoq",
    Examine: "Sinovdan o'tkazmoq",

    // "Accept": "Qabul qilmoq",
    // "Achieve": "Erishmoq",
    // "Act": "Amal qilmoq",
    // "Adapt": "Moslashtirmoq",
    // "Add": "Qo'shmoq",
    // "Admire": "Hayrat bilan qarashmoq",
    // "Advise": "Maslahat berish",
    // "Agree": "Kelishmoq",
    // "Aim": "Maqsad qilmoq",
    // "Analyze": "Tahlil qilmoq",
    // "Apologize": "Uzr so'ramoq",
    // "Apply": "Murojaat qilmoq",
    // "Appreciate": "Qadrlamoq",
    // "Approve": "Tasdiqlamoq",
    // "Argue": "Munozara qilmoq",
    // "Arrive": "Yetib kelmoq",
    // "Ask": "So'ralmoq",
    // "Assist": "Yordam bermoq",
    // "Attack": "Hujum qilmoq",
    // "Attract": "Jazolamoq",
    // "Bake": "Pishirmoq",
    // "Bathe": "Yuvmoq",
    // "Behave": "Ravishda bo'lmoq",
    // "Believe": "Ishonmoq",
    // "Belong": "Tegishli bo'lmoq",
    // "Bet": "Shart qo'yish",
    // "Borrow": "Qarz olmoq",
    // "Build": "Qurmoq",
    // "Buy": "Sotib olish",
    // "Calculate": "Hisoblash",
    // "Call": "Qo'ng'iroq qilmoq",
    // "Care": "E'tibor bermoq",
    // "Carry": "O'tkazmoq",
    // "Catch": "Tortmoq",
    // "Change": "O'zgartirmoq",
    // "Choose": "Tanlash",
    // "Clean": "Tozalash",
    // "Climb": "Chiqmoq",
    // "Collect": "To'plamoq",
    // "Come": "Kelmoq",
    // "Communicate": "Aloqada bo'lmoq",
    // "Compare": "Taqqoslash",
    // "Complain": "Shikoyat qilmoq",
    // "Complete": "Yakunlamoq",
    // "Contribute": "Qo'shimcha hissa qo'shmoq",
    // "Cook": "Oshirish",
    // "Cost": "Narxi",
    // "Count": "Hisoblash",
    // "Create": "Yaratmoq",
    // "Cry": "Yig'lamoq",
    // "Dance": "Raqs qilmoq",
    // "Decide": "Qaror qabul qilmoq",
    // "Decorate": "Suzmoq",
    // "Defend": "Difolat qilmoq",
    // "Delay": "To'xtatmoq",
    // "Deliver": "Yetkazib berish",
    // "Depend": "Bog'liq bo'lmoq",
    // "Describe": "Tavsif qilmoq",
    // "Design": "Dizayn qilmoq",
    // "Destroy": "Yok etmoq",
    // "Develop": "Rivojlantirmoq",
    // "Discover": "Topmoq",
    // "Discuss": "Munozara qilmoq",
    // "Divide": "Bo'lishmoq",
    // "Do": "Amal qilmoq",
    // "Dream": "Tushuntirmoq",
    // "Dress": "Libos kiyish",
    // "Drink": "Ichmoq",
    // "Drive": "Haydash",
    // "Earn": "Daromad qilmoq",
    // "Eat": "Yemoq",
    // "Edit": "Tahrirlamoq",
    // "Educate": "O'qitmoq",
    // "Embrace": "Qabul qilmoq",
    // "Employ": "Ishga olish",
    // "Encourage": "Yo'llamoq",
    // "Enjoy": "Mazza olish",
    // "Enter": "Kirish",
    // "Escape": "Qochmoq",
    // "Establish": "Tashkil qilmoq",
    // "Evaluate": "Baholamoq",
    // "Examine": "Sinovdan o'tkazmoq"
    // Add more translations here
  };

  const translation = translations[word];
  return translation ? translation : "Translation not found";
}

// Example usage
const word = "Achieve";
const translation = translateToUzbek(word);
console.log(`English: ${word}`);
console.log(`Uzbek: ${translation}`);
